apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: medical-monitoring
data:
  TUMBLING_INTERVAL: "5"
  SLIDING_WINDOW: "30"
  NATS_URL: "nats://nats:4222"
  ETCD_URL: "http://etcd:2379"
  REDIS_URL: "redis://redis:6379"
  JAEGER_URL: "http://jaeger:14268"
  LOG_LEVEL: "info"
