apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medical-monitoring

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- hpa.yaml
- service.yaml
- analyzer-deployment.yaml
- analyzer-hpa.yaml

commonLabels:
  managed-by: kustomize
  environment: production

images:
- name: medical-collector
  newTag: latest
- name: python-analyzer
  newTag: latest

replicas:
- name: medical-collector
  count: 3
- name: python-analyzer
  count: 2

patchesStrategicMerge:
- patches/collector-resources.yaml
